apiVersion: v1
kind: pod
metadata: 
  name: service-demo
  labels:    #these labels are used to recongnise this pod with service
    project: roboshop
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx